#!/bin/sh
# $Id$
#
# Copyright (C) 2003  rsdio
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
#
#    Free Software Foundation, Inc.,
#    59 Temple Place, Suite 330,
#    Boston, MA  02111-1307
#    USA

resolve_path() {
    local RPATH

#    RPATH=`realpath $1 2>/dev/null`
#    if [ $? -eq 0 ]; then
#        echo $RPATH
#        exit 0
#    fi
#
#    RPATH=`grealpath $1 2>/dev/null`
#    if [ $? -eq 0 ]; then
#        echo $RPATH
#        exit 0
#    fi
#    echo "one=$?"

    LAST="$0"
    RPATH=`readlink $LAST`
    if [ $? -ne 0 ] && [ $? -ne 1 ]; then
        exit 1
    fi
    if [ -z "$RPATH" ]; then
        echo $0
        exit 0
    fi

    while [ -n "$RPATH" ]; do
        LAST=$RPATH
        RPATH=`readlink $LAST`
    done

    echo $LAST
    exit 0
}

JAVAOPTS=
APPOPTS=
for OPT in "$@"; do
  case $OPT in
    -J*) JAVAOPTS="$JAVAOPTS $(echo $OPT | sed 's/^-J//')" ;;
    *) APPOPTS="$APPOPTS $OPT"
  esac
done

DIR=`resolve_path $0`
if [ -z "$DIR" ]; then
    DIR="$0"
fi
DIR=`dirname $DIR`
JAR="$DIR/target/jarsync-jar-with-dependencies.jar"

if [ ! -f $JAR ]; then
    JAR="$DIR/jarsync-jar-with-dependencies.jar"
fi
if [ ! -f $JAR ]; then
    echo "cannot find jarsync-jar-with-dependencies.jar"
fi

exec java -Djarsync.rsh=/usr/bin/ssh $JAVAOPTS -jar $JAR $APPOPTS

